      - View:
          style:
            flexDirection: column
            justifyContent: center
            backgroundColor: {bgdc}
            height: 650
            width: 400
            marginTop: 10
          children:
            - Text:
                index: 760
                style:
                  fontWeight: bold
                  fontFamily: Gurmukhi MN
                  color: {tc}
                  fontSize: 22
                  marginTop: 10
                  marginLeft: 20
            - TextInput: #address
                id: input_ad
                index: 840
                len: 100
                style:
                  width: 90%
                  height: 50
                  fontSize: 15
                  color: "#888888"
                  backgroundColor: {bgdc}
                  borderColor: {boc}
                  borderWidth: 1
                  marginTop: 10
                  marginLeft: 20
            - Text: #current location
                index: 1170
                style:
                  fontFamily: Gurmukhi MN
                  color: {tc}
                  fontSize: 20
                  marginTop: 15
                  marginLeft: 40
            - Text:
                index: 1045
                style:
                  fontFamily: Gurmukhi MN
                  color: {tc}
                  fontSize: 20
                  marginTop: 3
                  marginLeft: 40
            - Text:
                index: 970
                style:
                  fontWeight: bold
                  fontFamily: Gurmukhi MN
                  color: {tc}
                  fontSize: 22
                  marginTop: 40
                  marginLeft: 20
            - TextInput: #phone number
                id: input_phone
                index: 1010
                len: 11
                style:
                  width: 90%
                  height: 50
                  fontSize: 15
                  color: "#888888"
                  backgroundColor: {bgdc}
                  borderColor: {boc}
                  borderWidth: 1
                  marginTop: 10
                  marginLeft: 20
            - Text: #current phone num
                index: 1190
                style:
                  fontFamily: Gurmukhi MN
                  color: {tc}
                  fontSize: 20
                  marginTop: 15
                  marginLeft: 40
            - Text:
                index: 1140
                style:
                  fontFamily: Gurmukhi MN
                  color: {tc}
                  fontSize: 20
                  marginTop: 3
                  marginLeft: 40
            - Text: #payment
                index: 800
                style:
                  fontWeight: bold
                  fontFamily: Gurmukhi MN
                  color: {tc}
                  fontSize: 22
                  marginTop: 40
                  marginLeft: 20
            - Button:
                id: cash
                style: # box
                  width: 100
                  height: 40
                  alignItems: center
                  backgroundColor: {btc1}
                  borderRadius: 10
                  marginTop: 30
                  marginLeft: 60
                on_touch:
                  backgroundColor: rgb(255, 200, 0)
                children: 
                  - Text:
                      index: 940
                      style:
                        color: black
                        fontFamily: Gurmukhi MN
                        fontSize: 17
                        marginTop: 7
            - Button:
                id: ole
                style: # box
                  width: 100
                  height: 40
                  alignItems: center
                  backgroundColor: {btc2}
                  borderRadius: 10
                  marginTop: -40
                  marginLeft: 230
                on_touch:
                  backgroundColor: rgb(255, 200, 0)
                children: 
                  - Text:
                      index: 950
                      style:
                        color: black
                        fontFamily: Gurmukhi MN
                        fontSize: 17
                        marginTop: 7
